name: Publish VS Code Extension

on:
  push:
    branches:
      - main # Or your default/release branch

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Fetch all history for all tags and branches
          fetch-depth: 0
          # This is needed to push changes back
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18" # Or your preferred Node.js version

      - name: Install dependencies
        run: npm install

      - name: Install vsce
        run: npm install -g vsce

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"

      - name: Increment version, build, and package
        run: |
          npm version patch -m "chore(release): publish v%s"
          vsce package # Project uses npm (package-lock.json found)

      - name: Publish to Visual Studio Marketplace
        # The VSCE_PAT secret needs to be created in your GitHub repository settings
        # It should be a Personal Access Token from https://dev.azure.com/{your_organization}/_usersSettings/tokens
        run: vsce publish -p ${{ secrets.VS_MARKETPLACE_TOKEN }}

      - name: Push changes (version bump and tags)
        run: |
          git push --follow-tags
